<a href="https://colab.research.google.com/github/pedromsoares/Curso_EBA/blob/main/Notebooks/M%C3%B3dulo_Extra_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PANDAS

## Imoprta as bibliotecas

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive

## Carregar os datasets

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Curso EBA/Pandas/top10s.csv', encoding='ISO-8859-1')

In [ ]:
df2 = pd.read_csv('/content/drive/MyDrive/Curso EBA/Datasets/SpotifyTopSongsByCountry - May 2020.csv', encoding='ISO-8859-1')

### Informações sobre o Dataset 1

In [ ]:
df.head() #Exibe as 5 primeiras linhas do dataset

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [ ]:
df.tail() #Exibe as 5 ultimas linhas do dataset

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

In [ ]:
df.info() #Exibe informações básicas sobre o dataset (Nome das variáveis, Contagem de valores não nulos e Tipo de variáveis)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 603 entries, 0 to 602
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  603 non-null    int64
 1   title       603 non-null    object
 2   artist      603 non-null    object
 3   top genre   603 non-null    object
 4   year        603 non-null    int64
 5   bpm         603 non-null    int64
 6   nrgy        603 non-null    int64
 7   dnce        603 non-null    int64
 8   dB          603 non-null    int64
 9   live        603 non-null    int64
 10  val         603 non-null    int64
 11  dur         603 non-null    int64
 12  acous       603 non-null    int64
 13  spch        603 non-null    int64
 14  pop         603 non-null    int64
dtypes: int64(12), object(3)
memory usage: 70.8+ KB

### Informações sobre o Dataset 2

In [ ]:
df2.head()

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07

In [ ]:
df2.tail()

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
3145,Vietnam,Asia,46,ÄÃ Tá»ªNG LÃ,VÅ©.,ÄÃ Tá»ªNG LÃ,0,4:20
3146,Vietnam,Asia,47,MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,"BigDaddy, Emily",MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,0,3:18
3147,Vietnam,Asia,48,NgÃ y Táº­n Tháº¿,"TÃ³c TiÃªn, Da LAB, Touliver",NgÃ y Táº­n Tháº¿,0,3:52
3148,Vietnam,Asia,49,Äi Äu ÄÆ°a Äi,Bich Phuong,Äi Äu ÄÆ°a Äi,0,3:40
3149,Vietnam,Asia,50,Blinding Lights,The Weeknd,After Hours,0,3:20

In [ ]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3150 entries, 0 to 3149
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Country    3150 non-null   object
 1   Continent  3150 non-null   object
 2   Rank       3150 non-null   int64
 3   Title      3150 non-null   object
 4   Artists    3150 non-null   object
 5   Album      3150 non-null   object
 6   Explicit   3150 non-null   int64
 7   Duration   3150 non-null   object
dtypes: int64(2), object(6)
memory usage: 197.0+ KB

### Mostrar apenas colunas por tipo de variável

In [ ]:
df.select_dtypes(include='int64') #Exibe apenas as colunas com variáveis do tipo 'int64'

     Unnamed: 0  year  bpm  nrgy  dnce  dB  live  val  dur  acous  spch  pop
0             1  2010   97    89    67  -4     8   80  217     19     4   83
1             2  2010   87    93    75  -5    52   64  263     24    23   82
2             3  2010  120    84    76  -3    29   71  200     10    14   80
3             4  2010  119    92    70  -4     8   71  295      0     4   79
4             5  2010  109    84    64  -5     9   43  221      2     4   78
..          ...   ...  ...   ...   ...  ..   ...  ...  ...    ...   ...  ...
598         599  2019  104    66    61  -7    20   16  176      1     3   75
599         600  2019   95    79    75  -6     7   61  206     21    12   75
600         601  2019  136    76    53  -5     9   65  260      7    34   70
601         602  2019  114    79    60  -6    42   24  217      1     7   69
602         603  2019  150    44    70  -9    13   23  213      6     6   67

[603 rows x 12 columns]

In [ ]:
df.select_dtypes(include='object') #exibe apenas as colunas com variáveis do tipo 'object'

,title,artist,top genre
0,"Hey, Soul Sister",Train,neo mellow
1,Love The Way You Lie,Eminem,detroit hip hop
2,TiK ToK,Kesha,dance pop
3,Bad Romance,Lady Gaga,dance pop
4,Just the Way You Are,Bruno Mars,pop
...,...,...,...
598,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop
599,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop
600,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop
601,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop
602,Kills You Slowly,The Chainsmokers,electropop

### Trazer uma descrição estatística básica dos valores numéricos

In [ ]:
df.describe() #Exibe uma estatística básica do Dataset

,Unnamed: 0,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
count,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000,603.000000
mean,302.000000,2014.592040,118.545605,70.504146,64.379768,-5.578773,17.774461,52.225539,224.674959,14.326700,8.358209,66.520730
std,174.215384,2.607057,24.795358,16.310664,13.378718,2.798020,13.102543,22.513020,34.130059,20.766165,7.483162,14.517746
min,1.000000,2010.000000,0.000000,0.000000,0.000000,-60.000000,0.000000,0.000000,134.000000,0.000000,0.000000,0.000000
25%,151.500000,2013.000000,100.000000,61.000000,57.000000,-6.000000,9.000000,35.000000,202.000000,2.000000,4.000000,60.000000
50%,302.000000,2015.000000,120.000000,74.000000,66.000000,-5.000000,12.000000,52.000000,221.000000,6.000000,5.000000,69.000000
75%,452.500000,2017.000000,129.000000,82.000000,73.000000,-4.000000,24.000000,69.000000,239.500000,17.000000,9.000000,76.000000
max,603.000000,2019.000000,206.000000,98.000000,97.000000,-2.000000,74.000000,98.000000,424.000000,99.000000,48.000000,99.000000

### Realizar verificação dos valores únicos de uma coluna

In [ ]:
df['artist'].unique() #Retrona os valores únicos, sem repetição, da coluna selecionada

array(['Train', 'Eminem', 'Kesha', 'Lady Gaga', 'Bruno Mars',
       'Justin Bieber', 'Taio Cruz', 'OneRepublic', 'Alicia Keys',
       'Rihanna', 'Flo Rida', 'Mike Posner', 'Far East Movement', 'Usher',
       'Sean Kingston', 'The Black Eyed Peas', 'Adam Lambert', 'Maroon 5',
       'Neon Trees', 'Selena Gomez & The Scene', 'Enrique Iglesias',
       'Katy Perry', 'Britney Spears', '3OH!3', 'David Guetta',
       'Christina Aguilera', 'Florence + The Machine', 'Shakira',
       'Tinie Tempah', 'T.I.', 'Martin Solveig', 'Christina Perri',
       'Adele', 'Pitbull', 'Beyoncé', 'Hot Chelle Rae', 'Avril Lavigne',
       'Kanye West', 'LMFAO', 'Jessie J', 'Jennifer Lopez', 'Chris Brown',
       'Sleeping At Last', 'Nicki Minaj', 'P!nk', 'Coldplay',
       'One Direction', 'Taylor Swift', 'Carly Rae Jepsen',
       'Kelly Clarkson', 'Owl City', 'The Wanted', 'fun.',
       'Ellie Goulding', 'Gym Class Heroes', 'Avicii', 'The Script',
       'Miley Cyrus', 'Swedish House Mafia', 'Daft Punk', 'James Arthur',
       'Robin Thicke', 'Demi Lovato', 'Zedd', 'Lana Del Rey',
       'Calvin Harris', 'Drake', 'Sara Bareilles',
       'Macklemore & Ryan Lewis', 'Labrinth', 'Ne-Yo', 'Ariana Grande',
       'Justin Timberlake', 'will.i.am', 'Icona Pop', 'Fergie',
       'Little Mix', 'Emeli Sandé', 'Selena Gomez', 'Austin Mahone',
       'Jonas Brothers', 'Mariah Carey', 'Ciara', 'Jewel',
       'Kelly Rowland', 'John Legend', 'Sam Smith', 'Pharrell Williams',
       'MAGIC!', 'Passenger', 'Bastille', 'Lorde', 'John Newman',
       'Disclosure', 'Michael Jackson', '5 Seconds of Summer',
       'Iggy Azalea', 'Jason Derulo', 'The Chainsmokers', 'Birdy',
       'A Great Big World', 'Sia', 'Charli XCX', 'Lily Allen',
       'Lea Michele', 'Ed Sheeran', 'The Weeknd', 'Mark Ronson', 'Hozier',
       'Shawn Mendes', 'Mr. Probz', 'Zara Larsson', 'Fifth Harmony',
       'Clean Bandit', 'Meghan Trainor', 'Nick Jonas', 'Paloma Faith',
       'Olly Murs', 'Naughty Boy', 'Alessia Cara', 'Sigala', 'Rudimental',
       'Lost Frequencies', 'Robin Schulz', 'Lilly Wood and The Prick',
       'Wiz Khalifa', 'Alesso', 'Madonna', 'Gwen Stefani', 'Jess Glynne',
       'Hilary Duff', 'Ricky Martin', 'Jennifer Hudson', 'DNCE',
       'Martin Garrix', 'Lukas Graham', 'G-Eazy', 'Hailee Steinfeld',
       'BØRNS', 'Major Lazer', 'MØ', 'Tove Lo', 'ZAYN', 'Bebe Rexha',
       'Snakehips', 'Missy Elliott', 'Years & Years', 'Charlie Puth',
       'Janet Jackson', 'Joey Montana', 'Nelly Furtado', 'DJ Snake',
       'Kygo', 'DJ Khaled', 'Luis Fonsi', 'Camila Cabello', 'Jonas Blue',
       'CNCO', 'Cardi B', 'Alan Walker', 'Liam Payne', 'Niall Horan',
       'Cashmere Cat', 'Galantis', 'Dua Lipa', 'Silk City', 'Marshmello',
       'Halsey', 'Troye Sivan', 'Dan + Shay', 'Rita Ora', 'Harry Styles',
       'Ansel Elgort', 'J Balvin', 'N.E.R.D', 'Hayley Kiyoko', 'RedOne',
       'Lewis Capaldi', 'SHAED', 'Lizzo', 'Mabel', 'Khalid', 'R3HAB',
       'Daddy Yankee'], dtype=object)

In [ ]:
df['artist'].nunique() #Retorna a contagem de valores únicos da variável

184

In [ ]:
df.memory_usage() #Retorna a quantidade de memória utilizada por cada coluna

Index          128
Unnamed: 0    4824
title         4824
artist        4824
top genre     4824
year          4824
bpm           4824
nrgy          4824
dnce          4824
dB            4824
live          4824
val           4824
dur           4824
acous         4824
spch          4824
pop           4824
dtype: int64

### Saber os maiores e menores valores de uma coluna

In [ ]:
df.nsmallest(3, 'nrgy') #Retorna os 3 menores valores da coluna 'nrgy'

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
442,443,Million Years Ago,Adele,british soul,2016,0,0,0,-60,0,0,227,0,0,0
431,432,Start,John Legend,neo mellow,2016,110,4,52,-15,9,26,310,99,4,47
255,256,Not About Angels,Birdy,neo mellow,2014,116,14,41,-10,9,23,190,97,4,56

In [ ]:
df.nlargest(3, 'nrgy') #Retorna os 3 maiores valores da coluna 'nrgy'

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
50,51,Hello,Martin Solveig,big room,2010,128,98,67,-3,10,45,191,1,3,0
198,199,Pom Poms,Jonas Brothers,boy band,2013,148,98,68,-2,28,90,198,7,9,52
134,135,Don't Stop the Party (feat. TJR),Pitbull,dance pop,2012,127,96,72,-4,38,95,206,1,9,59

## Algumas operações com datasets

In [ ]:
df_nodup = df.drop_duplicates(subset=['title'], keep='last') #Cria um novo dataframe, excluíndo os valores duplicados e mantendo apenas o mais atual

In [ ]:
display(df_nodup)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,3,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

## Encontrar valores específicos em um dataframe

In [ ]:
df.query("artist == 'Ariana Grande'") #Quando se procura Strings deve-se usar aspas duplas no query

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
171,172,The Way,Ariana Grande,dance pop,2013,82,88,65,-3,8,86,227,29,11,68
221,222,Problem,Ariana Grande,dance pop,2014,103,81,66,-5,16,63,194,2,15,75
287,288,Love Me Harder,Ariana Grande,dance pop,2015,99,71,47,-4,8,24,236,1,3,76
291,292,Break Free,Ariana Grande,dance pop,2015,130,70,69,-5,20,28,215,1,5,75
323,324,Focus,Ariana Grande,dance pop,2015,100,88,67,-6,44,79,211,27,24,66
368,369,Into You,Ariana Grande,dance pop,2016,108,73,62,-6,14,37,244,2,11,80
381,382,Dangerous Woman,Ariana Grande,dance pop,2016,134,60,66,-5,36,29,236,5,4,78
451,452,Side To Side,Ariana Grande,dance pop,2017,159,74,65,-6,24,61,226,5,23,80
513,514,no tears left to cry,Ariana Grande,dance pop,2018,122,71,70,-6,29,35,206,4,6,84

In [ ]:
df.query("artist == 'Katy Perry'")

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
28,29,Teenage Dream,Katy Perry,dance pop,2010,120,80,72,-5,13,59,228,2,4,63
29,30,California Gurls,Katy Perry,dance pop,2010,125,75,79,-4,18,40,235,0,5,62
77,78,E.T.,Katy Perry,dance pop,2011,152,87,62,-5,37,76,230,2,18,66
101,102,Last Friday Night (T.G.I.F.),Katy Perry,dance pop,2011,126,81,65,-4,67,72,231,0,4,27
102,103,Firework,Katy Perry,dance pop,2011,124,83,64,-5,11,65,228,14,5,25
124,125,Part Of Me,Katy Perry,dance pop,2012,130,92,68,-5,7,77,216,0,4,71
127,128,Wide Awake,Katy Perry,dance pop,2012,160,68,51,-5,39,57,221,7,4,68
128,129,The One That Got Away,Katy Perry,dance pop,2012,134,80,69,-4,16,88,227,0,4,67
144,145,Roar,Katy Perry,dance pop,2013,180,77,55,-5,35,46,224,0,4,78
216,217,Dark Horse,Katy Perry,dance pop,2014,132,59,65,-6,17,35,216,0,5,78
237,238,This Is How We Do,Katy Perry,dance pop,2014,96,64,69,-6,15,80,204,2,5,66
242,243,Birthday,Katy Perry,dance pop,2014,126,67,72,-5,11,84,215,9,7,65
357,358,Legendary Lovers,Katy Perry,dance pop,2015,126,84,62,-5,8,39,224,2,8,41
408,409,Rise,Katy Perry,dance pop,2016,101,64,55,-6,11,44,203,5,5,66
468,469,Swish Swish,Katy Perry,dance pop,2017,120,71,84,-5,10,57,243,2,4,73
469,470,Chained To The Rhythm,Katy Perry,dance pop,2017,190,80,45,-5,20,47,238,8,17,72
485,486,Bon appétit,Katy Perry,dance pop,2017,106,79,80,-6,22,52,228,13,6,68

In [ ]:
df.query('dur > 200') #Quando a procura é numérica, podemos usar as aspas simples

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,14,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
596,597,"Taki Taki (feat. Selena Gomez, Ozuna & Cardi B)",DJ Snake,electronic trap,2019,96,80,84,-4,6,62,213,16,23,77
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,12,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,34,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,7,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,6,67

## Operações com Dataframe

In [ ]:
df_nodup.drop(columns=['spch'], inplace=True) #Excluo a coluna spch do dataframe e com inplace naõ tem mais como retornar

/usr/local/lib/python3.7/dist-packages/pandas/core/frame.py:4913: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
df_nodup.head()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77

In [ ]:
df_nodup['dur'].mean() #Calcula a média da coluna dur

224.63698630136986

In [ ]:
df_nodup['dur'].min() #Retorna o valor mínimo para a variável (o método .max() retorna o valor máximo)

134

In [ ]:
df_nodup.agg({'acous':'mean', 'dur':'max'}) #retorna os valores de média e máximo das colunas que estão no dicionário

acous     14.152397
dur      424.000000
dtype: float64

In [ ]:
df_nodup.assign(energy_dance = lambda df : df['dnce']*df['nrgy']) #Cria uma nova coluna que é a multriplicaçaõ dos valores de nrgy e dnce

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop,energy_dance
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83,5963
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82,6975
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80,6384
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79,6440
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77,6278
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,75,4026
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,75,5925
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,70,4028
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,69,4740
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,67,3080

### Groupby

In [ ]:
df.groupby('artist').count()

,Unnamed: 0,title,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
artist,,,,,,,,,,,,,,
3OH!3,1,1,1,1,1,1,1,1,1,1,1,1,1,1
5 Seconds of Summer,1,1,1,1,1,1,1,1,1,1,1,1,1,1
A Great Big World,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Adam Lambert,2,2,2,2,2,2,2,2,2,2,2,2,2,2
Adele,10,10,10,10,10,10,10,10,10,10,10,10,10,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
ZAYN,5,5,5,5,5,5,5,5,5,5,5,5,5,5
Zara Larsson,1,1,1,1,1,1,1,1,1,1,1,1,1,1
Zedd,6,6,6,6,6,6,6,6,6,6,6,6,6,6
fun.,2,2,2,2,2,2,2,2,2,2,2,2,2,2
will.i.am,1,1,1,1,1,1,1,1,1,1,1,1,1,1

In [ ]:
df.groupby('artist')['title'].count()

artist
3OH!3                   1
5 Seconds of Summer     1
A Great Big World       1
Adam Lambert            2
Adele                  10
                       ..
ZAYN                    5
Zara Larsson            1
Zedd                    6
fun.                    2
will.i.am               1
Name: title, Length: 184, dtype: int64

In [ ]:
df.groupby(['artist', 'year'])['title'].count() #Agrupamento com a lista das colunas

artist               year
3OH!3                2010    1
5 Seconds of Summer  2014    1
A Great Big World    2014    1
Adam Lambert         2010    2
Adele                2011    2
                            ..
Zedd                 2015    1
                     2016    1
                     2017    2
fun.                 2012    2
will.i.am            2013    1
Name: title, Length: 409, dtype: int64

In [ ]:
df.groupby(['artist', 'year']).agg({'year':'count', 'dur':'mean'}) #Faço um agrupamento pelo artista e o ano e realizo a contagem do ano e a média da duração

                          year    dur
artist              year
3OH!3               2010     1  192.0
5 Seconds of Summer 2014     1  202.0
A Great Big World   2014     1  229.0
Adam Lambert        2010     2  227.5
Adele               2011     2  256.5
...                        ...    ...
Zedd                2015     1  240.0
                    2016     1  225.0
                    2017     2  207.5
fun.                2012     2  264.0
will.i.am           2013     1  280.0

[409 rows x 2 columns]

In [ ]:
df_group_year = df.groupby('year') #novo dataframe com agrupamento por ano

In [ ]:
df_group_year.ngroups #Retorna o número de grupos criados

10

In [ ]:
df_group_year.groups #Retorna um dicionário com os grupos (anos) e os índíces dos dados

{2010: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50], 2011: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103], 2012: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138], 2013: [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209], 2014: [210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267], 2015: [268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362], 2016: [363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442], 2017: [443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507], 2018: [508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571], 2019: [572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602]}

In [ ]:
df_group_year.size() #Retorna o tamanho dos grupos

year
2010    51
2011    53
2012    35
2013    71
2014    58
2015    95
2016    80
2017    65
2018    64
2019    31
dtype: int64

In [ ]:
df_group_year.get_group(2015) #Retorna o grupo de 2015

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
268,269,Thinking out Loud,Ed Sheeran,pop,2015,79,45,78,-6,18,59,282,47,3,84
269,270,I'm Not The Only One,Sam Smith,pop,2015,82,49,68,-6,8,49,239,53,4,84
270,271,The Hills,The Weeknd,canadian contemporary r&b,2015,113,56,58,-7,14,14,242,7,5,84
271,272,Love Yourself,Justin Bieber,canadian pop,2015,100,38,61,-10,28,52,234,84,44,83
272,273,Uptown Funk,Mark Ronson,dance pop,2015,115,61,86,-7,3,93,270,1,8,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,359,Spark The Fire,Gwen Stefani,dance pop,2015,120,80,88,-4,20,54,202,8,6,39
359,360,Run Run Run,Kelly Clarkson,dance pop,2015,112,37,28,-7,11,8,273,45,4,36
360,361,Let Me Be Your Lover,Enrique Iglesias,dance pop,2015,112,90,72,-4,6,88,238,1,13,34
361,362,Dangerous,Jennifer Hudson,dance pop,2015,109,53,90,-5,8,65,255,0,5,18
362,363,L.A.LOVE (la la),Fergie,dance pop,2015,202,39,48,-8,26,27,193,2,9,0

## Merging Dataframes

O .merge() funciona como o left join do SQL.

![inner-join-left-join-outer-join.png]()

In [34]:
df.merge(df2, left_on='artist', right_on='Artists', how='left').fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,0,0,0.0,0,0,0,0.0,0
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,0,0,0.0,0,0,0,0.0,0
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,0,0,0.0,0,0,0,0.0,0
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,0,0,0.0,0,0,0,0.0,0
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,0,0,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,0,0,0.0,0,0,0,0.0,0
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,0,0,0.0,0,0,0,0.0,0
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,0,0,0.0,0,0,0,0.0,0
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,0,0,0.0,0,0,0,0.0,0
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,0,0,0.0,0,0,0,0.0,0

In [35]:
df.merge(df2, left_on='artist', right_on='Artists', how='left', indicator=True) #Une os dataframes como antes, mas o parâmetro indicator adiciona uma coluna dizendo em qual dataframe a variável estava

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration,_merge
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

### Concatenando operações

In [38]:
df_grouped = (df
              .groupby('artist')
              ['title']
              .count()
              .to_frame()
              .reset_index()
              )

In [39]:
df_grouped

                  artist  title
0                  3OH!3      1
1    5 Seconds of Summer      1
2      A Great Big World      1
3           Adam Lambert      2
4                  Adele     10
..                   ...    ...
179                 ZAYN      5
180         Zara Larsson      1
181                 Zedd      6
182                 fun.      2
183            will.i.am      1

[184 rows x 2 columns]